### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by lgwapnitsky** [5t3ph/eleventy-plugin-social-images#4]
when running with documented config:

```
lgwapnitsky@blog:~/lgw_11ty$ eleventy-social-images --site-name "Larry G. Wapnitsky"
Starting social images...
(node:18860) UnhandledPromiseRejectionWarning: SyntaxError: /home/lgwapnitsky/lgw_11ty/pages.json: Unexpected number in JSON at position 1
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /home/lgwapnitsky/lgw_11ty/node_modules/@11tyrocks/eleventy-plugin-social-images/bin/social-images.js:82:17
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:18860) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18860) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

pages.json file:

```
---
permalink: ./pages.json
permalinkBypassOutputDir: true
eleventyExcludeFromCollections: true
---
[
{%- for pages in collections.all %}
    {
      "title":"{{ pages.data.title | addNbsp | safe }}",
      "imgName":"{{ pages.data.title | slug }}"
    }{% if loop.last == false %},{% endif -%}
{% endfor %}
]
```

**Comment by 5t3ph** [comment]
Hi @lgwapnitsky - just to clarify, the file that creates the JSON should actually be a Nunjucks file (ex. `pages.njk`) and you may need to adjust your permalink to ensure it places it outside of your Eleventy `input` directory. There can also be issues with permalinks that aren't placed in quotes `"./pages.json"`

Check on those things, and let me know if you resolve it.

**Comment by lgwapnitsky** [comment]
where would the njk file go and what would it look like? if i rename pages.json, i get an error that that file doesn't exist.

also, putting pages.json in quotes didn't work
