### ISSUE TITLE
Social images not building

### ISSUE THREAD

**Issue by bebsico** [5t3ph/eleventy-plugin-social-images#8]
Running `npm run build` I get following:

> Starting social images...
> (node:11969) UnhandledPromiseRejectionWarning: Error: Cannot find module 'puppeteer-core/lib/cjs/puppeteer/common/Browser'
> Require stack:
> - /home/bebsico/projects/desnellebij.be/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js
> - /home/bebsico/projects/desnellebij.be/node_modules/chrome-aws-lambda/source/index.js
> - /home/bebsico/projects/desnellebij.be/node_modules/@11tyrocks/eleventy-plugin-social-images/bin/social-images.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/home/bebsico/projects/desnellebij.be/node_modules/chrome-aws-lambda/source/puppeteer/lib/Browser.js:6:11)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:11969) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:11969) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

And I don't have a clue to what to do with that.

**Comment by nachtfunke** [comment]
I believe you need to install puppeteer on your system to fix this: `npm install -g puppeteer`
